name: Internal Lint
on:
  pull_request:
    paths: ["**.yml", "**.yaml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  call:
    uses: ./.github/workflows/reusable-workflows.yml
    permissions:
      contents: read
