name: Lint Composite Action
on:
  workflow_call:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  call:
    uses: tmknom/lint-workflows/.github/workflows/reusable-workflows.yml@v0
    permissions:
      contents: read
