name: Lint Composite Action
on:
  workflow_call:
    outputs:
      yamllint-configuration-sha256:
        value: ${{ jobs.lint.outputs.yamllint-configuration-sha256 }}
        description: SHA256 of the configuration file to passing yamllint.

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      yamllint-configuration-sha256: ${{ steps.yamllint.outputs.configuration-sha256 }}
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Cross Yamllint
        id: yamllint
        uses: tmknom/cross-yamllint-action@4140cdcbc0cf1bcc05e15a7f5b3822314df48486 # v0.3.0
        with:
          configuration-url: https://raw.githubusercontent.com/tmknom/configurations/v0.3.0/yamllint/composite-action.yml

      - name: Secure actionlint
        uses: tmknom/secure-actionlint-action@87e303e3f6a0abc082812068119eee7e8f24630e # v0.1.0
