name: Lint GitHub Actions
on:
  workflow_call:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Cross Yamllint
        uses: tmknom/cross-yamllint-action@4140cdcbc0cf1bcc05e15a7f5b3822314df48486 # v0.3.0
        with:
          configuration-url: https://raw.githubusercontent.com/tmknom/configurations/v0.3.0/yamllint/github-actions.yml

      - name: Run actionlint
        run: |
          set -x
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
